FUNCTION IFEXIST(p_param VARCHAR2, p_tabla VARCHAR2, p_value VARCHAR2)
RETURN NUMBER
AS
v_exist NUMBER(4);
v_query VARCHAR2(2)
BEGIN
SELECT COUNT(*) INTO v_exist FROM p_tabla WHERE p_value = p_param;
RETURN v_exist;
END IFEXIST;

if (IFEXIST("25","CENTROS","NUMERO_CENTRO") = 0)

if (IFEXIST("QUIJOTE","CENTROS","NOMBRE_CENTRO") = 0)


insert into centros values((select (max(cod_centro)+1)) from centros), 
	(select TIPO_CENTRO FROM CENTROS WHERE COD_CENTRO = p_centro), 
	CONCAT('AUX_',CONCAT((SELECT NOMBRE_CENTRO FROM CENTROS WHERE COD_CENTRO = p_centro),'_ELIMINADO'))



	SELECT COD_CENTRO, TIPO_CENTRO,NOMBRE,DIRECCION,TELEFONO,NUM_PLAZAS FROM CENTROS WHERE COD_CENTRO=15;